<?php

/**
 * <!--
 * This file is part of the adventure php framework (APF) published under
 * http://adventure-php-framework.org.
 *
 * The APF is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The APF is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with the APF. If not, see http://www.gnu.org/licenses/lgpl-3.0.txt.
 * -->
 */
import('tools::http', 'HeaderManager');
import('tools::link', 'LinkGenerator');

/**
 * @package modules::usermanagement::biz::login
 * @class UmgtLogoutAction
 *
 * This front controller action logs out the user and initializes a redirect
 * to the desired logout page. The url is generated by the logout url provider.
 *
 * @author Christian Achatz
 * @version
 * Version 0.1, 03.06.2011<br />
 */
class UmgtLogoutAction extends AbstractFrontcontrollerAction {

   public function run() {
      $logout = $this->getInput()->getAttribute('logout', 'false');
      if ($logout === 'true') {
         $sessionStore = &$this->getServiceObject('modules::usermanagement::biz', 'UmgtUserSessionStore', APFObject::SERVICE_TYPE_SESSIONSINGLETON);
         /* @var $sessionStore UmgtUserSessionStore */
         $sessionStore->logout($this->getApplicationIdentifier());

         // redirect to target page
         $urlProvider = &$this->getDIServiceObject('modules::usermanagement::biz', 'LogoutRedirectUrlProvider');
         /* @var $urlProvider UmgtRedirectUrlProvider */
         HeaderManager::forward(LinkGenerator::generateUrl(Url::fromString($urlProvider->getRedirectUrl())));

      }
   }

   private function getApplicationIdentifier() {
      return $this->getInput()->getAttribute('app-ident', $this->getContext());
   }

}

?>